In [177]:
import numpy as np
import pandas as pd

In [178]:
df=pd.read_csv('Training.csv')

In [179]:
df

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4915  ...           0         0             0                    0   
4916  ...           1         1             0                    0   
4917  ...           0         0             0                    0   
4918  ...           0         0             1                    1   
4919  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4915                     0                   0        0                     0   
4916                     0                   0        0                     0   
4917                     0                   0        0                     0   
4918                     1                   1        0                     0   
4919                     0                   0        1                     1   

      yellow_crust_ooze                                prognosis  
0                     0                         Fungal infection  
1                     0                         Fungal infection  
2                     0                         Fungal infection  
3                     0                         Fungal infection  
4                     0                    

In [180]:
df.shape

(4920, 133)

In [181]:
column_list = df.columns.tolist()
column_list

['itching',
 'skin_rash',
 'nodal_skin_eruptions',
 'continuous_sneezing',
 'shivering',
 'chills',
 'joint_pain',
 'stomach_pain',
 'acidity',
 'ulcers_on_tongue',
 'muscle_wasting',
 'vomiting',
 'burning_micturition',
 'spotting_ urination',
 'fatigue',
 'weight_gain',
 'anxiety',
 'cold_hands_and_feets',
 'mood_swings',
 'weight_loss',
 'restlessness',
 'lethargy',
 'patches_in_throat',
 'irregular_sugar_level',
 'cough',
 'high_fever',
 'sunken_eyes',
 'breathlessness',
 'sweating',
 'dehydration',
 'indigestion',
 'headache',
 'yellowish_skin',
 'dark_urine',
 'nausea',
 'loss_of_appetite',
 'pain_behind_the_eyes',
 'back_pain',
 'constipation',
 'abdominal_pain',
 'diarrhoea',
 'mild_fever',
 'yellow_urine',
 'yellowing_of_eyes',
 'acute_liver_failure',
 'fluid_overload',
 'swelling_of_stomach',
 'swelled_lymph_nodes',
 'malaise',
 'blurred_and_distorted_vision',
 'phlegm',
 'throat_irritation',
 'redness_of_eyes',
 'sinus_pressure',
 'runny_nose',
 'congestion',
 'chest_pain',


In [182]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4920.000000  4920.000000           4920.000000          4920.000000   
mean      0.137805     0.159756              0.021951             0.045122   
std       0.344730     0.366417              0.146539             0.207593   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4920.000000  4920.000000  4920.000000   4920.000000  4920.000000   
mean      0.021951     0.162195     0.139024      0.045122     0.045122   
std       0.146539     0.368667     0.346007      0.207593     0.207593   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4920.000000  ...         4920.000000  4920.000000  4920.000000   
mean           0.021951  ...            0.021951     0.021951     0.021951   
std            0.146539  ...            0.146539     0.146539     0.146539   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4920.000000          4920.000000           4920.000000   
mean       0.023171             0.023171              0.023171   
std        0.150461             0.150461              0.150461   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4920.000000  4920.000000           4920.000000   
mean             0.023171     0.023171              0.023171   
std              0.150461     0.150461              0.150461   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4920.000000  
mean            0.023171  
std             0.150461  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [183]:
df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [184]:
import joblib as jb
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [185]:
X=df.iloc[:,0:132]
Y=df['prognosis']

In [186]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [187]:
Y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [188]:
le=LabelEncoder()

In [189]:
Y=le.fit_transform(Y)

In [190]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [191]:
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))

In [193]:
df['prognosis'].nunique()

41

In [192]:
for label, encoded_value in label_mapping.items():
    print(f"{label}: {encoded_value}")

(vertigo) Paroymsal  Positional Vertigo: 0
AIDS: 1
Acne: 2
Alcoholic hepatitis: 3
Allergy: 4
Arthritis: 5
Bronchial Asthma: 6
Cervical spondylosis: 7
Chicken pox: 8
Chronic cholestasis: 9
Common Cold: 10
Dengue: 11
Diabetes : 12
Dimorphic hemmorhoids(piles): 13
Drug Reaction: 14
Fungal infection: 15
GERD: 16
Gastroenteritis: 17
Heart attack: 18
Hepatitis B: 19
Hepatitis C: 20
Hepatitis D: 21
Hepatitis E: 22
Hypertension : 23
Hyperthyroidism: 24
Hypoglycemia: 25
Hypothyroidism: 26
Impetigo: 27
Jaundice: 28
Malaria: 29
Migraine: 30
Osteoarthristis: 31
Paralysis (brain hemorrhage): 32
Peptic ulcer diseae: 33
Pneumonia: 34
Psoriasis: 35
Tuberculosis: 36
Typhoid: 37
Urinary tract infection: 38
Varicose veins: 39
hepatitis A: 40


In [194]:
from sklearn.preprocessing import StandardScaler

In [195]:
ss=StandardScaler()

In [196]:
from sklearn.model_selection import train_test_split

In [197]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.6,random_state=42)

In [198]:
X_train

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4228        0          0                     0                    0   
4795        0          1                     0                    0   
1239        1          1                     1                    0   
2289        0          0                     0                    0   
2740        0          0                     0                    0   
...       ...        ...                   ...                  ...   
4426        0          1                     0                    0   
466         0          0                     0                    0   
3092        0          1                     0                    0   
3772        1          1                     1                    0   
860         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4228          0       0           0             0        0                 0   
4795          0       0           1             0        0                 0   
1239          0       0           0             0        0                 0   
2289          0       0           1             0        0                 0   
2740          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4426          0       0           1             0        0                 0   
466           0       0           0             0        0                 0   
3092          0       1           1             0        0                 0   
3772          0       0           0             0        0                 0   
860           0       0           0             1        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4228  ...                   0           0         0             0   
4795  ...                   0           0         0             1   
1239  ...                   0           0         0             0   
2289  ...                   0           0         0             0   
2740  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4426  ...                   0           0         0             1   
466   ...                   0           0         0             0   
3092  ...                   0           0         0             0   
3772  ...                   0           0         0             0   
860   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4228                    0                     0                   0        0   
4795                    1                     1                   1        0   
1239                    0                     0                   0        0   
2289                    0                     0                   0        0   
2740                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4426                    1                     1                   1        0   
466                     0                     0                   0        0   
3092                    0                     0                   0        0   
3772                    0                     0                   0        0   
860                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4228                     0                  0  
4795                     0                  0  
1239                     0                  0  
2289                     0                  0  
2740                     0                  0  
...                    ...                ...  
4426                     0                  0  
466               

In [199]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
373         0          1                     0                    0   
4916        0          1                     0                    0   
1550        0          0                     0                    0   
3081        0          0                     0                    0   
3857        1          0                     0                    0   
...       ...        ...                   ...                  ...   
2474        1          0                     0                    0   
2542        1          1                     1                    0   
1246        0          0                     0                    1   
1208        0          0                     0                    0   
216         0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
373           0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
1550          0       0           0             0        0                 0   
3081          0       0           0             0        0                 0   
3857          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2474          0       0           0             0        0                 0   
2542          0       0           0             0        0                 0   
1246          0       1           0             0        0                 0   
1208          0       0           0             0        0                 0   
216           0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
373   ...                   0           1         1             0   
4916  ...                   1           1         1             0   
1550  ...                   0           0         0             0   
3081  ...                   0           0         0             0   
3857  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2474  ...                   0           0         0             0   
2542  ...                   0           0         0             0   
1246  ...                   0           0         0             0   
1208  ...                   0           0         0             0   
216   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
373                     0                     0                   0        0   
4916                    0                     0                   0        0   
1550                    0                     0                   0        0   
3081                    0                     0                   0        0   
3857                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2474                    0                     0                   0        0   
2542                    0                     0                   0        0   
1246                    0                     0                   0        0   
1208                    0                     0                   0        0   
216                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
373                      0                  0  
4916                     0                  0  
1550                     0                  0  
3081                     0                  0  
3857                     0                  0  
...                    ...                ...  
2474                     0                  0  
2542              

In [200]:
Y_train

array([33, 35, 15, ..., 11, 15, 14])

In [201]:
Y_test

array([ 2,  2, 24, ...,  4, 38, 20])

In [202]:
model=RandomForestClassifier(max_depth=5, min_samples_split=2, min_samples_leaf=1)

In [203]:
model.fit(X_train,Y_train)

RandomForestClassifier(max_depth=5)

In [204]:
input_data=X.iloc[0,:]

In [205]:
input_data

itching                 1
skin_rash               1
nodal_skin_eruptions    1
continuous_sneezing     0
shivering               0
                       ..
small_dents_in_nails    0
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
Name: 0, Length: 132, dtype: int64

In [206]:
type(input_data)

pandas.core.series.Series

In [207]:
input_data=input_data.values

In [208]:
input_data

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [209]:
input_data.shape

(132,)

In [210]:
input_data=input_data.reshape(1,-1)

In [211]:
input_data

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [212]:
input_data.shape

(1, 132)

In [213]:
Y_pred=model.predict(input_data)

C:\Users\Soumya Samanta\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [214]:
Y_pred

array([18])

In [215]:
from sklearn.metrics import accuracy_score

In [216]:
Y_pred=model.predict(X_test)

In [217]:
Y_pred

array([ 2,  2, 24, ...,  4, 38, 20])

In [218]:
import joblib as jb

In [221]:
max=0;
for i in range(1,1000):
    accuracy=accuracy_score(Y_pred,Y_test)
    if(accuracy>=max):
        max=accuracy
if(max>=0.90):
    print("The accuracy of the model is ",max)
    jb.dump(model,'diseasepred.pkl')
    print("Model saved succesfully")
else:
    print("The accuracy of the model is ",max)
    print("Model not saved")

The accuracy of the model is  0.9153116531165312
Model saved succesfully


In [220]:
import os
file_name='diseasepred.pkl'
current_directory=os.getcwd()
absolute_path=os.path.join(current_directory,file_name)
print(absolute_path)

C:\Users\Soumya Samanta\diseasepred.pkl
